// 困ったfgets。解決策が見つかるまでは見なかったことにしよう。

#include<stdio.h>
#include<string.h>
#define I (128)
#define J (8)

int main() {

  char buf[I][J];
  int i;
  int broken = I;

  for (i = 0; i < I; i++) {
    printf("%3d番目の文字列を入力してください: ", i+1);
    fgets(buf[i], J-1, stdin);
    if (strncmp(buf[i], "break", 5) == 0) {
      broken = i;
      break;
    }
  }

  for (i = 0; i < broken; i++)
    printf("入力された%3d番目の文字列は%sです.\n", i+1, buf[i]);


  return 0;
}

/*
[is0243rk@MD1MS088 week04]$ ./overflow-fgets 
  1番目の文字列を入力してください: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  2番目の文字列を入力してください:   3番目の文字列を入力してください:   4番目の文字列を入力してください:   5番目の文字列を入力してください:   6番目の文字列を入力してください:   7番目の文字列を入力してください:   8番目の文字列を入力してください:   9番目の文字列を入力してください:  10番目の文字列を入力してください:  11番目の文字列を入力してください:  12番目の文字列を入力してください:  13番目の文字列を入力してください:  14番目の文字列を入力してください:  15番目の文字列を入力してください:  16番目の文字列を入力してください:  17番目の文字列を入力してください:  18番目の文字列を入力してください:  19番目の文字列を入力してください:  20番目の文字列を入力してください:  21番目の文字列を入力してください:  22番目の文字列を入力してください:  23番目の文字列を入力してください:  24番目の文字列を入力してください:  25番目の文字列を入力してください:  26番目の文字列を入力してください:  27番目の文字列を入力してください:  28番目の文字列を入力してください:  29番目の文字列を入力してください:  30番目の文字列を入力してください:  31番目の文字列を入力してください:  32番目の文字列を入力してください:  33番目の文字列を入力してください:  34番目の文字列を入力してください:  35番目の文字列を入力してください:  36番目の文字列を入力してください:  37番目の文字列を入力してください:  38番目の文字列を入力してください:  39番目の文字列を入力してください:  40番目の文字列を入力してください:  41番目の文字列を入力してください:  42番目の文字列を入力してください:  43番目の文字列を入力してください:  44番目の文字列を入力してください:  45番目の文字列を入力してください:  46番目の文字列を入力してください:  47番目の文字列を入力してください:  48番目の文字列を入力してください:  49番目の文字列を入力してください:  50番目の文字列を入力してください:  51番目の文字列を入力してください:  52番目の文字列を入力してください:  53番目の文字列を入力してください:  54番目の文字列を入力してください:  55番目の文字列を入力してください:  56番目の文字列を入力してください:  57番目の文字列を入力してください:  58番目の文字列を入力してください:  59番目の文字列を入力してください:  60番目の文字列を入力してください:  61番目の文字列を入力してください:  62番目の文字列を入力してください:  63番目の文字列を入力してください:  64番目の文字列を入力してください:  65番目の文字列を入力してください:  66番目の文字列を入力してください:  67番目の文字列を入力してください:  68番目の文字列を入力してください:  69番目の文字列を入力してください:  70番目の文字列を入力してください:  71番目の文字列を入力してください:  72番目の文字列を入力してください:  73番目の文字列を入力してください:  74番目の文字列を入力してください:  75番目の文字列を入力してください:  76番目の文字列を入力してください:  77番目の文字列を入力してください:  78番目の文字列を入力してください:  79番目の文字列を入力してください:  80番目の文字列を入力してください:  81番目の文字列を入力してください:  82番目の文字列を入力してください:  83番目の文字列を入力してください:  84番目の文字列を入力してください:  85番目の文字列を入力してください:  86番目の文字列を入力してください:  87番目の文字列を入力してください:  88番目の文字列を入力してください:  89番目の文字列を入力してください:  90番目の文字列を入力してください:  91番目の文字列を入力してください:  92番目の文字列を入力してください:  93番目の文字列を入力してください:  94番目の文字列を入力してください:  95番目の文字列を入力してください:  96番目の文字列を入力してください:  97番目の文字列を入力してください:  98番目の文字列を入力してください:  99番目の文字列を入力してください: 100番目の文字列を入力してください: 101番目の文字列を入力してください: 102番目の文字列を入力してください: 103番目の文字列を入力してください: 104番目の文字列を入力してください: 105番目の文字列を入力してください: 106番目の文字列を入力してください: 107番目の文字列を入力してください: 108番目の文字列を入力してください: 109番目の文字列を入力してください: 110番目の文字列を入力してください: 111番目の文字列を入力してください: 112番目の文字列を入力してください: 113番目の文字列を入力してください: 114番目の文字列を入力してください: 115番目の文字列を入力してください: 116番目の文字列を入力してください: 117番目の文字列を入力してください: 118番目の文字列を入力してください: 119番目の文字列を入力してください: 120番目の文字列を入力してください: 121番目の文字列を入力してください: 122番目の文字列を入力してください: 123番目の文字列を入力してください: 124番目の文字列を入力してください: 125番目の文字列を入力してください: 126番目の文字列を入力してください: 127番目の文字列を入力してください: 128番目の文字列を入力してください: 入力された  1番目の文字列はaaaaaaです.
入力された  2番目の文字列はaaaaaaです.
入力された  3番目の文字列はaaaaaaです.
入力された  4番目の文字列はaaaaaaです.
入力された  5番目の文字列はaaaaaaです.
入力された  6番目の文字列はaaaaaaです.
入力された  7番目の文字列はaaaaaaです.
入力された  8番目の文字列はaaaaaaです.
入力された  9番目の文字列はaaaaaaです.
入力された 10番目の文字列はaaaaaaです.
入力された 11番目の文字列はaaaaaaです.
入力された 12番目の文字列はaaaaaaです.
入力された 13番目の文字列はaaaaaaです.
入力された 14番目の文字列はaaaaaaです.
入力された 15番目の文字列はaaaaaaです.
入力された 16番目の文字列はaaaaaaです.
入力された 17番目の文字列はaaaaaaです.
入力された 18番目の文字列はaaaaaaです.
入力された 19番目の文字列はaaaaaaです.
入力された 20番目の文字列はaaaaaaです.
入力された 21番目の文字列はaaaaaaです.
入力された 22番目の文字列はaaaaaaです.
入力された 23番目の文字列はaaaaaaです.
入力された 24番目の文字列はaaaaaaです.
入力された 25番目の文字列はaaaaaaです.
入力された 26番目の文字列はaaaaaaです.
入力された 27番目の文字列はaaaaaaです.
入力された 28番目の文字列はaaaaaaです.
入力された 29番目の文字列はaaaaaaです.
入力された 30番目の文字列はaaaaaaです.
入力された 31番目の文字列はaaaaaaです.
入力された 32番目の文字列はaaaaaaです.
入力された 33番目の文字列はaaaaaaです.
入力された 34番目の文字列はaaaaaaです.
入力された 35番目の文字列はaaaaaaです.
入力された 36番目の文字列はaaaaaaです.
入力された 37番目の文字列はaaaaaaです.
入力された 38番目の文字列はaaaaaaです.
入力された 39番目の文字列はaaaaaaです.
入力された 40番目の文字列はaaaaaaです.
入力された 41番目の文字列はaaaaaaです.
入力された 42番目の文字列はaaaaaaです.
入力された 43番目の文字列はaaaaaaです.
入力された 44番目の文字列はaaaaaaです.
入力された 45番目の文字列はaaaaaaです.
入力された 46番目の文字列はaaaaaaです.
入力された 47番目の文字列はaaaaaaです.
入力された 48番目の文字列はaaaaaaです.
入力された 49番目の文字列はaaaaaaです.
入力された 50番目の文字列はaaaaaaです.
入力された 51番目の文字列はaaaaaaです.
入力された 52番目の文字列はaaaaaaです.
入力された 53番目の文字列はaaaaaaです.
入力された 54番目の文字列はaaaaaaです.
入力された 55番目の文字列はaaaaaaです.
入力された 56番目の文字列はaaaaaaです.
入力された 57番目の文字列はaaaaaaです.
入力された 58番目の文字列はaaaaaaです.
入力された 59番目の文字列はaaaaaaです.
入力された 60番目の文字列はaaaaaaです.
入力された 61番目の文字列はaaaaaaです.
入力された 62番目の文字列はaaaaaaです.
入力された 63番目の文字列はaaaaaaです.
入力された 64番目の文字列はaaaaaaです.
入力された 65番目の文字列はaaaaaaです.
入力された 66番目の文字列はaaaaaaです.
入力された 67番目の文字列はaaaaaaです.
入力された 68番目の文字列はaaaaaaです.
入力された 69番目の文字列はaaaaaaです.
入力された 70番目の文字列はaaaaaaです.
入力された 71番目の文字列はaaaaaaです.
入力された 72番目の文字列はaaaaaaです.
入力された 73番目の文字列はaaaaaaです.
入力された 74番目の文字列はaaaaaaです.
入力された 75番目の文字列はaaaaaaです.
入力された 76番目の文字列はaaaaaaです.
入力された 77番目の文字列はaaaaaaです.
入力された 78番目の文字列はaaaaaaです.
入力された 79番目の文字列はaaaaaaです.
入力された 80番目の文字列はaaaaaaです.
入力された 81番目の文字列はaaaaaaです.
入力された 82番目の文字列はaaaaaaです.
入力された 83番目の文字列はaaaaaaです.
入力された 84番目の文字列はaaaaaaです.
入力された 85番目の文字列はaaaaaaです.
入力された 86番目の文字列はaaaaaaです.
入力された 87番目の文字列はaaaaaaです.
入力された 88番目の文字列はaaaaaaです.
入力された 89番目の文字列はaaaaaaです.
入力された 90番目の文字列はaaaaaaです.
入力された 91番目の文字列はaaaaaaです.
入力された 92番目の文字列はaaaaaaです.
入力された 93番目の文字列はaaaaaaです.
入力された 94番目の文字列はaaaaaaです.
入力された 95番目の文字列はaaaaaaです.
入力された 96番目の文字列はaaaaaaです.
入力された 97番目の文字列はaaaaaaです.
入力された 98番目の文字列はaaaaaaです.
入力された 99番目の文字列はaaaaaaです.
入力された100番目の文字列はaaaaaaです.
入力された101番目の文字列はaaaaaaです.
入力された102番目の文字列はaaaaaaです.
入力された103番目の文字列はaaaaaaです.
入力された104番目の文字列はaaaaaaです.
入力された105番目の文字列はaaaaaaです.
入力された106番目の文字列はaaaaaaです.
入力された107番目の文字列はaaaaaaです.
入力された108番目の文字列はaaaaaaです.
入力された109番目の文字列はaaaaaaです.
入力された110番目の文字列はaaaaaaです.
入力された111番目の文字列はaaaaaaです.
入力された112番目の文字列はaaaaaaです.
入力された113番目の文字列はaaaaaaです.
入力された114番目の文字列はaaaaaaです.
入力された115番目の文字列はaaaaaaです.
入力された116番目の文字列はaaaaaaです.
入力された117番目の文字列はaaaaaaです.
入力された118番目の文字列はaaaaaaです.
入力された119番目の文字列はaaaaaaです.
入力された120番目の文字列はaaaaaaです.
入力された121番目の文字列はaaaaaaです.
入力された122番目の文字列はaaaaaaです.
入力された123番目の文字列はaaaaaaです.
入力された124番目の文字列はaaaaaaです.
入力された125番目の文字列はaaaaaaです.
入力された126番目の文字列はaaaaaaです.
入力された127番目の文字列はaaaaaaです.
入力された128番目の文字列はaaaaaaです.
[is0243rk@MD1MS088 week04]$ aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bash: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: コマンドが見つかりません
[is0243rk@MD1MS088 week04]$ 
*/
